spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/dogs
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
logs.url=http://${LOGS_HOST:localhost}:8081/api/v1/logs
